spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: gatman
    password: gatman

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: vaniagatman@gmail.com
    password: sffakyrofiixmbut
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  ssl:
    key-store-type: PKCS12
    key-store: src/main/resources/keystore/baeldung.p12
    key-store-password: gatman
    key-alias: baeldung
    enabled: true





faker:
  uri: https://jsonplaceholder.typicode.com/users
  jwtSecret: jsonfakerSecretKey
  jwtExpirationMs: 1800000 #30 min

logging:
  file:
    path: src/main/resoureces/faker.log


csv:
  filename: "jsonFakerUsers.csv"

