spring:

#     datasource:
#       url: jdbc:postgresql://localhost:5432/postgres
#       username: postgres
#       password: postgres

     mvc:
      pathmatch:
        matching-strategy: ant_path_matcher


server:
  port: 8080


faker:
  uri: https://jsonplaceholder.typicode.com/users
  jwtSecret: jsonfakerSecretKey
  jwtExpirationMs: 1800000 #30 min

logging:
  file:
    path: src/main/resoureces/faker.log

