spring:
#    datasource:
#      url: jdbc:postgresql://db:5432/postgres
#      username: postgres
#      password: postgres

server:
  port: 8080

faker:
  uri: https://jsonplaceholder.typicode.com/users
  jwtSecret: jsonfakerSecretKey
  jwtExpirationMs: 1800000 #30 min

logging:
  file:
    path: src/main/resoureces/faker.log