spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: gatman
    password: gatman
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

faker:
  uri: https://jsonplaceholder.typicode.com/users
  jwtSecret: jsonfakerSecretKey
  jwtExpirationMs: 1800000 #30 min

logging:
  file:
    path: src/main/resoureces/faker.log

